### ISSUE TITLE
using your flac lib

### ISSUE THREAD

**Issue by alfsch1** [astoeckel/libfoxenflac#1]
Hello,
i just build a small audio player, with STM32F411 (ARM F4 core at 100MHz)  from SDcard to DAC, at first only wav ; but now i tried also MP3 and flac ...
and so i tried your lib , for flac decoding. It is working fine now, CPU load about 35% (with SDIO access times).
Thanks for your good work. :)

**Comment by astoeckel** [comment]
Awesome, glad to hear this!
