### ISSUE TITLE
No samples output when decoding short files

### ISSUE THREAD

**Issue by ZoneMR** [astoeckel/libfoxenflac#9]
When playing back a short audio file, such as the one attached, no audio output samples are produced.

[deny.flac.zip](https://github.com/user-attachments/files/16758675/deny.flac.zip)

**Comment by WickedSmoke** [comment]
The `flac_decoder.c` example emits 511 samples from `deny.flac`.   I'm noticing that the last few thousand samples are missing from other FLAC files as well.

**Comment by astoeckel** [comment]
The decoder example incorrectly exited the main loop once the input file was done, and not once the decoder was done.

I've changed the `flac_decoder.c` termination logic to match the one in the integration test.

This should be fixed now! Thanks again for letting me know.

**Comment by WickedSmoke** [comment]
The output is correct now, but the "Copy unread bytes" loop needs an `if (in_buf_len)` check for when `fx_flac_process()` doesn't consume any input.  Right now it needlessly copies the entire in_buf over itself.

**Comment by astoeckel** [comment]
Sure, thanks, I fixed that as well (though this didn't affect correctness, and this is really just silly example code).
